# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IDKYvxqL6A8b_vOYrzhJzLd8k65DUqy
"""

a = int(input("Введите значение a: "))
b = int(input("Введите значение b: "))
ab = 20+5
ab = 25**2
print (ab)

a = input("Введите значение a: ")

b = input("Введите значение b: ")

a = int(a)
b = int(b)

sum_ab = a + b

result = sum_ab ** 2

print(f"Сумма a и b: {sum_ab}")
print(f"Сумма в квадрате: {result}")

a = 15
b = 10

c = input("Введите значение C: ")

c = int(c)

sum_ab = a + b

if c == 0:
    print("Ошибка: деление на ноль недопустимо.")
else:
  result = sum_ab / c

  print(f"Сумма a и b: {sum_ab}")

a = input("Введите значение a: ")
b = input("Введите значение b: ")

a = float(a)
b = float(b)

sum_ab = a + b

square_of_sum = sum_ab ** 2

formula = f"({a} + {b})^2 = {square_of_sum}"

print(formula)

import math

a = float(input("Введите длину стороны a: "))
b = float(input("Введите длину стороны b: "))
c = float(input("Введите длину стороны c: "))

if a + b > c and a + c > b and b + c > a:

    perimeter = a + b + c

    s = perimeter / 2

    area = math.sqrt(s * (s - a) * (s - b) * (s - c))

    print(f"Периметр треугольника: {perimeter}")
    print(f"Площадь треугольника: {area}")
else:
    print("Ошибка: введенные значения не могут образовать треугольник.")

a = float(input("Введите значение a: "))
b = float(input("Введите значение b: "))

result = ((a ** 3 + 14) / 5) * b

print(f"Результат выражения ((a^3 + 14) / 5) * b: {result}")

number = float(input("Введите число для возведения в квадрат: "))

n = float(input("Введите число n для деления на него: "))

square = number ** 2

if n != 0:
    result = square // n
    print(f"Квадрат числа {number} равен {square}. Результат деления {square} на {n} без остатка: {result}")
else:
    print("Ошибка: Деление на ноль невозможно.")