# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQpVxjc2HWWLF_0CtoBRw3PAEtEzz9Rk
"""

a=int(input())
if a==1:
  print('ЯНВАРЬ')
elif a==2:
  print('ФЕВРАЛЬ')
elif a==3:
  print('МАРТ')
elif a==4:
  print('АПРЕЛЬ')
elif a==5:
  print('МАЙ')
elif a==6:
  print('ИЮНЬ')
elif a==7:
  print('ИЮЛЬ')
elif a==8:
  print('АВГУСТ')
elif a==9:
  print('СЕНТЯБРЬ')
elif a==10:
  print('ОКТЯБРЬ')
elif a==11:
  print('НОЯБРЬ')
elif a==12:
  print('ДЕКАБРЬ')

a=int(input('ВВЕДИТЕ ЧИСЛО n'))
if a % 2!=0:
  print('НЕ ЧЁТНОЕ')
else:
  print('ЧЁТНОЕ')

a=int(input('ВВЕДИТЕ ЧИСЛО n'))
if a>40:
  print('STONKS')
else:
  print('NOT STONKS')

def is_year_leap(a):
  if a % 4 == 0: # and  a%==
    return True
  else:
    return False
is_year_leap(int(input("ВВедите год"))