# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzMwmLw35rXAJWkfbojdb6cvtEzLKEV1
"""

N = int(input("Введите число N: "))

if N > 40:
    print("stonks")
else:
    print("not stonks")

def is_year_leap(year):

    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

year = int(input("Введите год: "))
if is_year_leap(year):
    print(f"{year} является високосным годом.")
else:
    print(f"{year} не является високосным годом.")

def is_prime(n):

    if n < 2:
        return False

    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

number = int(input("Введите число: "))
if is_prime(number):
    print(f"{number} является простым числом.")
else:
    print(f"{number} не является простым числом.")

a = float(input("Введите значение первой переменной (a): "))
b = float(input("Введите значение второй переменной (b): "))

lower_bound = (-138 / 2) ** 1.3
upper_bound = abs((-69 / (28 ** 5.1)) * 4)

if a > b * 3.6 or ((lower_bound <= b <= upper_bound)):
    a, b = b, a

print(f"Значение первой переменной (a): {a}")
print(f"Значение второй переменной (b): {b}")

numbers = []
for i in range(5):
    num = float(input(f"Введите число {i + 1}: "))
    numbers.append(num)

unique_numbers = set(numbers)
are_unique = len(unique_numbers) == len(numbers)

count_even = sum(1 for num in numbers if num % 2 == 0)
count_negative = sum(1 for num in numbers if num < 0)
count_in_range = sum(1 for num in numbers if -256 <= num <= 1024)

print(f"Все числа уникальны: {are_unique}")
print(f"Количество четных чисел: {count_even}")
print(f"Количество отрицательных чисел: {count_negative}")
print(f"Количество чисел в промежутке [-256 ; 1024]: {count_in_range}")

a = float(input("Введите значение a: "))
b = float(input("Введите значение b: "))
c = float(input("Введите значение c: "))

result = (a**2 + b**3) / (c + 3 / 4)

print(f"Результат неравенства: {result}")

if result % 2 == 0:
    print("Результат является четным числом.")
else:
    print("Результат является нечетным числом.")