# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FOXJiUe1XTTklyROWMDmMWw5tjKv8_fY
"""

a = 5
b = 2



c = a + b
print(c)

S = 0,5
B = 7,5
H = 7,5

с = 0,5 * 7,5 * 7,5
print (c)

x = (a ** 2 + b ** 2 - c** 3)/2
print (x)

