# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agT_Qk-tHnyKr8vsV-FU0T-8Qjeev_sy
"""

fahrenheit_values = [32, 50, 68, 86, 104]

kelvin_values = []
for F in fahrenheit_values:
    K = (F - 32) * 5 / 9 + 273.15
    kelvin_values.append(K)
    print(f"Температура в Фаренгейтах: {F}°F, в Кельвинах: {K:.2f} K")

for K in kelvin_values:
    if K % 2 == 0:
        print(f"{K:.2f} K является четным числом.")
    else:
        print(f"{K:.2f} K является нечетным числом.")

import matplotlib.pyplot as plt
import numpy as np

x = np.random.rand(50) * 100
y = np.random.rand(50) * 100

data = np.random.normal(0, 1, 1000)

labels = ['A', 'B', 'C', 'D']
sizes = [15, 30, 45, 10]
colors = ['gold', 'lightcoral', 'lightskyblue', 'lightgreen']

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.scatter(x, y, color='blue')
plt.title('График рассеяния')
plt.xlabel('X значения')
plt.ylabel('Y значения')

plt.subplot(1, 3, 2)
plt.hist(data, bins=30, color='green', alpha=0.7)
plt.title('Гистограмма')
plt.xlabel('Значения')
plt.ylabel('Частота')

plt.subplot(1, 3, 3)
plt.pie(sizes, labels=labels, colors=colors, autopct='%1.1f%%', startangle=140)
plt.title('Круговая диаграмма')

plt.tight_layout()
plt.show()

import math

print("Число Эйлера:", math.e)

print("Число Пи:", math.pi)

print("NaN:", math.nan)

journal_number = 4

factorial_value = math.factorial(journal_number)
print(f"Факториал числа {journal_number}: {factorial_value}")

phone_memory = 256

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

greatest_divisor = gcd(journal_number, phone_memory)
print(f"Наибольший делитель для чисел {journal_number} и {phone_memory}: {greatest_divisor}")

import matplotlib.pyplot as plt
import numpy as np

def draw_circle(ax, center, radius, color):
    circle = plt.Circle(center, radius, color=color)
    ax.add_artist(circle)

fig, ax = plt.subplots()

ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)
ax.set_aspect('equal')
ax.axis('off')

draw_circle(ax, (0, 0), 1, 'gray')

draw_circle(ax, (-0.7, 0.7), 0.3, 'darkgray')
draw_circle(ax, (0.7, 0.7), 0.3, 'darkgray')

draw_circle(ax, (-0.3, 0), 0.15, 'white')
draw_circle(ax, (0.3, 0), 0.15, 'white')
draw_circle(ax, (-0.3, 0), 0.07, 'black')
draw_circle(ax, (0.3, 0), 0.07, 'black')

draw_circle(ax, (0, -0.2), 0.1, 'pink')

ax.plot([-0.5, -0.1], [-0.2, -0.2], color='black', lw=2)
ax.plot([-0.5, -0.1], [-0.25, -0.25], color='black', lw=2)
ax.plot([-0.5, -0.1], [-0.15, -0.15], color='black', lw=2)

ax.plot([0.1, 0.5], [-0.2, -0.2], color='black', lw=2)
ax.plot([0.1, 0.5], [-0.25, -0.25], color='black', lw=2)
ax.plot([0.1, 0.5], [-0.15, -0.15], color='black', lw=2)

ax.plot([-0.2, 0.2], [-0.3, -0.3], color='black', lw=2)

plt.title('Котик')
plt.show()

